services:

  mysql:

    image: mysql:8.4

    container_name: expense-mysql

    restart: always

    environment:

      MYSQL_DATABASE: expense_tracker

      MYSQL_USER: expense_user

      MYSQL_PASSWORD: expense_password

      MYSQL_ROOT_PASSWORD: root_password

    ports:

      - "3307:3306"

    volumes:

      - mysql-data:/var/lib/mysql

  app:

    build: .

    container_name: expense-tracker

    restart: always

    ports:

      - "8080:8080"

    depends_on:

      - mysql

volumes:

  mysql-data: